### ISSUE TITLE
BioCro doesn't install on OSX

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/biocro#1]
When I try to install this version ([v0.93](https://github.com/ebimodeling/biocro/tree/v0.93) of BioCro on my mac, I get the following errors:

```
$ git clone git@github.com:ebimodeling/biocro
$ R CMD INSTALL biocro

```

> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/dlebauer/R/library/BioCro/libs/BioCro.so':
  dlopen(/Users/dlebauer/R/library/BioCro/libs/BioCro.so, 6): Symbol not found: _BiocroToCrocent
  Referenced from: /Users/dlebauer/R/library/BioCro/libs/BioCro.so
  Expected in: flat namespace
 in /Users/dlebauer/R/library/BioCro/libs/BioCro.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/dlebauer/R/library/BioCro’

If I try the devtools package, I get a different error (though both seem to relate to the coupling of DayCent.

```
library(devtools)
install_github("ebimodeling/biocro")

```

> Assigncropcent.c:440:3: warning: implicit declaration of function
      'GetLeachingParms' is invalid in C99 [-Wimplicit-function-declaration]
  GetLeachingParms(&CROPCENT->ENV.ORGLECH,getleachingparmsfromR);
  ^
Assigncropcent.c:631:6: error: conflicting types for 'GetLeachingParms'
void GetLeachingParms (struct OrgLeachParms *temp,double *getleachingparmsfromR)
     ^
Assigncropcent.c:440:3: note: previous implicit declaration is here
  GetLeachingParms(&CROPCENT->ENV.ORGLECH,getleachingparmsfromR);
  ^
8 warnings and 1 error generated.
make: *** [Assigncropcent.o] Error 1
ERROR: compilation failed for package ‘BioCro’
* removing ‘/Users/dlebauer/R/library/BioCro’
Error: Command failed (1)
> q()

It works on Windows, Ubuntu, and RedHat operating systems. Has anyone else had this issue (or else know how to resolve it?)

**Comment by justinmcgrath** [comment]
Does the latest change fix it?

**Comment by dlebauer** [comment]
@justinmcgrath I don't see any recent commits - note that this is on the public version ebimodeling/biocro so is probably something you've already fixed in the biocro-dev repository.

**Comment by djaiswal** [comment]
@dlebauer 
I have not worked on Mac.
I did not realize that this part of the code was in public version. Justin has found similar errors (multiple & conflicting declaration). I will come back to work on this on Biocro-dev later. I think this issue was already revolved by Justin in the biocro-dev branch.

**Comment by justinmcgrath** [comment]
I moved the function call after its declaration. I think now you'll just see a different error though. There should be a header file with the function declarations in it.

**Comment by dlebauer** [comment]
`install_github` works; `R CMD INSTALL` still doesn't. However, I am closing this. If the issue re-appears it may be resolved by setting the compiler settings in `~/.R/Makevars` file as described here: http://stackoverflow.com/questions/19503995/error-when-with-xcode-5-0-and-rcpp-command-line-tools-are-installed and here: https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Compilation-flags
