### ISSUE TITLE
totalradiation threshold

### ISSUE THREAD

**Issue by jessicaguo** [ebimodeling/biocro#16]
When running with the attached weather file, I received an error message of "total radiation too high", which originates [here](https://github.com/ebimodeling/biocro/blob/5c5d0a1325018a5a3d80d4e162762ed2ed7f81d2/src/AuxBioCro.c#L500) due to solar radiation exceeding 650 W/m^2.  

However, in the comments above it is noted that "On a clear sky it may exceed 1000 in some parts of the world  Thornley and Johnson pg 400". 

After raising the threshold to 1000, I was able to run the model successfully. @femiguez , should the threshold be raised to 1000 in all cases?

[weather.out.2020.xlsx](https://github.com/ebimodeling/biocro/files/5968445/weather.out.2020.xlsx)

**Comment by justinmcgrath** [comment]
This was changed when the models were changed to the new design (the new-framework branch). That branch hasn't been brought to master yet, because it will break other people's scripts.

**Comment by dlebauer** [comment]
can we remove the check here: https://github.com/ebimodeling/biocro/blob/5c5d0a1325018a5a3d80d4e162762ed2ed7f81d2/src/AuxBioCro.c#L500 from the master branch? This won't break anyone's scripts.

Isn't it sufficient for users to rely on the package version number so that their scripts won't break? Or are there no plans to merge the new version of the code?

**Comment by justinmcgrath** [comment]
I removed the check from master, although I think one would be better off using the new-framework branch.

> Isn't it sufficient for users to rely on the package version number so that their scripts won't break? Or are there no plans to merge the new version of the code?
R doesn't let you keep two versions of the same package installed, and people apparently have automated scripts that read directly from this repository based on some previous issues posted. There's a paper in progress about the new framework, and we'll merge when that is submitted. Then people's scripts will break, but the new framework will be at a point where the interface won't change, so further changes shouldn't cause breaks.

**Comment by dlebauer** [comment]
Thanks! If it breaks anyone's scripts they can get previous versions with e.g.:

```r
devtools::install_github("ebimodeling/biocro@0.951") 
```

I'll add this to the README
