### ISSUE TITLE
Add install instructions using `remotes::install_github()`?

### ISSUE THREAD

**Issue by Aariq** [ebimodeling/biocro#24]
Another, possibly easier, way to install `BioCro` without manual downloading is with 

```
remotes::install_github("ebiomodeling/biocro")
```

The `remotes` package obviously has to be installed first.

**Comment by eloch216** [comment]
Thanks, this is a great suggestion. The installation instructions were copied from the development version of BioCro which is in a private repository, which makes `remotes::install_github` more of a hassle to use, so we didn't include it as an option. But it makes sense to add it here.
