### ISSUE TITLE
management in biocro

### ISSUE THREAD

**Issue by istfer** [ebimodeling/biocro#27]
Hi, 

Does biocro simulate management events such as harvest & fertilization? I couldn't see how these would be passed to simulations at the first glance. Does it not take management into account or have I missed it? I would appreciate if you could point me in the right directions, thanks in advance!

**Comment by justinmcgrath** [comment]
Hi Istem,
Harvest is the end of the simulation. The models here were originally focused on annuals, so there is not a clean way to handle perennial crops, but that could be done by running the model with an ending time in Autumn, then starting a new run using the values from the previous run as initial conditions. Conceivably one could model the physiological changes in the winter, but that isn't done presently, and with the willow model for example, multiple runs have been used.

For other aspects of management, most would handled with what we call the "drivers" of the model. Irrigation could be included in the precipitation driver. Fertilizer could be added as a new driver. For fertilizer in particular though, the crop models have been developed assuming that farmer inputs are not limiting, so the present models do not use any information about fertilizer. There is some work to incorporate N uptake and distribution and to scale crop performance based on N, but that work isn't ready yet.

**Comment by istfer** [comment]
Thank you very much for the explanation, this helps a lot.
