### ISSUE TITLE
Installation error in Windows

### ISSUE THREAD

**Issue by sruthi162114001** [ebimodeling/biocro#28]
I am unable to install Biocro in windows as it throws the following error. Linux installation was okay without any error.

* installing *source* package 'BioCro' ...
** using staged installation
** libs

*** arch - i386
C:/PROGRA~ 1/R/R-4.1.2/etc/i386/Makeconf:260: warning: overriding recipe for target '.m.o'
C:/PROGRA~ 1/R/R-4.1.2/etc/i386/Makeconf:253: warning: ignoring old recipe for target '.m.o'
make: *** No rule to make target '$(CXX11STD)''.  Stop.
ERROR: compilation failed for package 'BioCro'
* removing 'C:/Users/Sruthi/Documents/R/win-library/4.1/Biocro2/BioCro'
Warning in install.packages :
  installation of package ‘D:/IITPKD/PhD_ESSENCE_IITPKD_Git/EGU2023/biocro/BioCro_2.0.0.tar.gz’ had non-zero exit status

**Comment by sruthi162114001** [comment]
This looks like an issue specific to my system. Although any help on this would be appreciated

**Comment by justinmcgrath** [comment]
It appears to be an issue with makefiles given that targets are overridden and CXX11STD is not defined. Do you have Rtools installed? Do you have custom makefiles in your R paths, either in the biocro directory, your R user directory or the R system directory? It would help to know what steps you took during installation.

**Comment by sruthi162114001** [comment]
Thank you for the response justin. I had more than one Rtool package installed and only one of them added to the system path. I am not sure if that was the issue but i was able to install BioCro once i removed all of it and reinstalled just one Rtool package and add it to the path.
