### ISSUE TITLE
Transpiration due to elevated CO2

### ISSUE THREAD

**Issue by pnlfang** [ebimodeling/biocro#3]
I did a test to see the effect of elevated CO2 for the C3 canopy model.  Assimilation goes up as expected, but transpiration didn't change.  Shouldn't it go up as well?  

Thanks,
Yilin

**Comment by djaiswal** [comment]
Canopy standalone function assumes no water limitation. Perhaps, you will see a stronger effect of CO2 when water is limited.

**Comment by justinmcgrath** [comment]
Can you provide the code you used to produce the result?

**Comment by pnlfang** [comment]
It can be tested using c3photo.R coming with the package.  I tested Catm = 450 ppm and 800 ppm.

**Comment by justinmcgrath** [comment]
I'm afraid I can't find what you're referring to. c3photo() returns stomatal conductance, assimilation and internal CO2 concentration, but not transpiration rate. In the code below, Gs is lower and Assim is higher in r800 compared to r450, so it responds as expected.
```
r450 = c3photo(Qp=1500, Tl=25, RH=0.8, Catm=450) 
r800 = c3photo(Qp=1500, Tl=25, RH=0.8, Catm=800)
```

c3CanA() calculates transpiration. In the code below, it is lower, but only slightly so. Is that what you're referring to?

```
r450 = c3CanA(lai=4, doy=150, hr=12, solar=1200, temp=30, rh=0.8, windspeed=1, c3photoControl=c3photoParms(Catm=450))
r800 = c3CanA(lai=4, doy=150, hr=12, solar=1200, temp=30, rh=0.8, windspeed=1, c3photoControl=c3photoParms(Catm=800))
```

**Comment by justinmcgrath** [comment]
There was no follow up, so I'm closing this.
